name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout ${{ github.ref_name }} ${{ github.ref_type }}
        uses: actions/checkout@v3

      - name: SSH and deploy forum-api
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ~/dicoding-forum-api
            git pull origin main
            npm ci
            npm run pgm up
            pm2 restart dicoding-forum-api
